### PR TITLE
Use `semver` package for handling semantic versioning

### LINKED ISSUE #11: Versions are incorrectly sorted
As seen [here](https://procedure-rpc.github.io/procedure.js):
image

### PR DESCRIPTION
**Pull request by toebeann**
## Changes in this PR
- Fixes #11 
- Refactored all functions that work with semantic versioning to make use of [`semver`](https://www.npmjs.com/package/semver) - the package [used by `npm` for working with semantic versioning](https://www.npmjs.com/package/npm?activeTab=dependencies)

### Reasoning
[On one of my own packages](https://procedure-rpc.github.io/procedure.js), I found that typedoc-plugin-versions was incorrectly sorting version numbers in the dropdown version selector:
image

This appears to be due to the fact that you are using a basic alphanumeric reverse sorting operation, which is insufficient. As such, I determined the only way to rectify this would be to correctly implement semver sorting, and the most effective way to do this would be to use the same package that npm itself uses when it comes to handling semantic versioning.

With this change, after some testing, I can get the following output, which shows the versions correctly sorted as expected:
image

I reasoned that it is best to ensure that anywhere the package touches semantic versioning that it does so in a consistent manner that is in line with the spec. As such, I refactored every function that touches semantic versioning to use the [`semver`](https://www.npmjs.com/package/semver) package.

Additionally, upgrading semver logic to rely on the [`semver`](https://www.npmjs.com/package/semver) package makes it easy to handle more advanced logical operations, e.g:
 - #10 

### Implementation details
- Added a dependency on [`semver`](https://www.npmjs.com/package/semver) 
- Refactored functions that work with semantic versioning to make use of [`semver`](https://www.npmjs.com/package/semver)
- Simplified some logic
- Dropped some now-redundant type exports
- Added more versions in the stubs to test version sorting
- Updated tests as necessary
- Bumped to version `0.2.0` as the exports have been changed
- Added myself as a `contributor` in package.json

### CODE REVIEW

File: src/etc/utils.ts [hunk 1]
```diff
@@ -23,109 +18,80 @@ const pack = fs.readJSONSync(packagePath);
  * @returns The package version
  * @todo grab potential labels from the version and provide them as further pegs in the menu.
  */
-export function getSemanticVersion(
-	version: string | null = pack.version
-): patchVersion {
+export function getSemanticVersion(version: string = pack.version): version {
```
Comment (citkane) [inline src/etc/utils.ts:21]: I prefer to leave the `version: string | null = pack.version` so that we can get test coverage on the error handler.

File: test/index.spec.ts [hunk 2]
```diff
@@ -33,11 +34,6 @@ describe('Unit testing for typedoc-plugin-versions', function () {
 				'did not provided a correctly formatted patch version'
 			);
 		});
-		it('throws error if version not defined', function () {
```
Comment (citkane) [inline test/index.spec.ts:36]: Let's keep this test in place.

**Comment by toebeann** [comment]
I'll address these comments this evening 👍

File: test/index.spec.ts (hunk 2 above)
Comment (toebeann) [reply test/index.spec.ts:36]: Resolved by 148563f91a206b97b60f4642f2dd985b0acced72

File: src/etc/utils.ts (hunk 1 above)
Comment (toebeann) [reply src/etc/utils.ts:21]: The issue with leaving the `| null` is that it can mislead you into thinking that passing `null` is an acceptable use of the function while working with the function in TypeScript, but doing so will _always_ result in an `Error` being thrown. This somewhat goes against the point of using TypeScript!

If the intention is to allow for testing the thrown Error, you can do that without allowing `null` in TS:
https://github.com/toebeann/typedoc-plugin-versions/blob/148563f91a206b97b60f4642f2dd985b0acced72/test/index.spec.ts#L37-L42
```ts
               it('throws error if version not defined', function () {
			assert.throws(() => {
				// @ts-expect-error: Intentionally passing a falsy value to test the error condition.
				vUtils.getSemanticVersion(null);
			}, 'Package version was not found');
		});
```
In the above, the `@ts-expect-error` directive tells the TypeScript compiler that we know what we're doing, and to ignore the fact that `null` does not match the expected argument type, and TS allows it to compile and the test passes as expected :). We could also achieve the same thing without the `@ts-expect-error` directive like this:
```ts
				vUtils.getSemanticVersion(<unknown>null as string);
```
And likewise TypeScript would allow it to compile, but it is quite ugly and doesn't convey the intention of the type cast.

Alternatively, we could write additional tests in a JavaScript *.spec.js file where anything goes.

Comment (toebeann) [reply src/etc/utils.ts:21]: Resolved by 148563f91a206b97b60f4642f2dd985b0acced72

**Comment by toebeann** [comment]
@citkane Done with changes in here :)
